### ISSUE TITLE
Missing busybox.lst

### ISSUE THREAD

**Issue by s243a** [techrockedge/archpup32#1]
Following peebee's steps when I run ./3builddistro

I saw the message,
"Please use the 'official' woofce busybox .pet package.."

From the code I can see that the script exits here (although it doesn't tell you there is an error even though it should):
```
# busybox applets...
if [ ! -f packages-${DISTRO_FILE_PREFIX}/busybox/bin/busybox.lst ] ; then
	echo "Please use the 'official' woofce busybox .pet package.."
	exit 1
fi
```
[/woof-code/3builddistro#L318](https://github.com/puppylinux-woof-CE/woof-CE/blob/d6226f43505c545a7d8eea4e4922b1807d5f58f3/woof-code/3builddistro#L318)

This is a list of apps included with busybox. It is generated via:
```
lst=$(./bin/busybox --list-full)
if [ "$lst" ] ; then
	echo "$lst" > /tmp/busybox.lst
elif [ -f ./bin/busybox.lst ] ; then
	cp -f ./bin/busybox.lst /tmp/busybox.lst
else
	echo "ERROR: could not get applet list"
	exit 1
fi
```
[woof-code/support/busybox_symlinks.sh#L25](https://github.com/puppylinux-woof-CE/woof-CE/blob/835aa140eed449a45d20bcb737aa0fb6d8e1193c/woof-code/support/busybox_symlinks.sh#L25)

**Comment by s243a** [comment]
So the code I'm talking about which creates the list of busybox aps, is called after the point at which the code exists. 
```
cp -a -f packages-${DISTRO_FILE_PREFIX}/busybox/bin/busybox* ./sandbox3/rootfs-complete/bin/
./support/busybox_symlinks.sh sandbox3/rootfs-complete
```
[/woof-code/3builddistro#L323](https://github.com/puppylinux-woof-CE/woof-CE/blob/d6226f43505c545a7d8eea4e4922b1807d5f58f3/woof-code/3builddistro#L323)
In other words if the .lst file never existed then it will never be created! 

I could simply move this code prior to the point where the code exists if it doesn't exist. Alternativly, If the .lst file doesn't exists then I could create a prompt asking if the user wants this file automatically created (or is going to manually create it). Once the user makes his/her selection and optionally (manually creates the list), then the code tests again if the file exists (in a loop). 

Before I do any of this though, I should confirm, that no one else is having this issue. Perhaps I did something wrong.

**Comment by s243a** [comment]
This looks related:
```
yes|busybox|busybox|exe,dev>null,doc,nls # arch version - package template needed
```

So, what I think this is saying is we want to use the arch version of busybox rather than the woof-CE version of busybox. In this case the script shouldn't exit. PResumably the "package template" would create the busybox.lst

**Comment by s243a** [comment]
I see that there is a "package template" to create the .list file:

```

#!/bin/sh

#arch
mkdir -p ./bin
mv usr/bin/* ./bin
rm -rf usr/bin

cp ../00_apup32_fix/bin/busybox.lst ./bin
```
[/packages-templates/busybox_FIXUPHACK](https://github.com/techrockedge/archpup32/blob/master/packages-templates/busybox_FIXUPHACK)

What I think might of happened is by me pressing cntrl-c in the middle of ./2createpackages might of left status flags which indicated that the package list was successfully created, and this caused the code to exit before all the "FIXUPHACKS" were finished. 

On my second run I got this message:
```
Exiting from support/findpkgs, already created up-to-date pkg list:
 /mnt/home/git_madness/archpup32/woof-CE/woof-out_arch32/status/findpkgs_FINAL_PKGS-arch-32
```

which is from the following part of the code:
```
if [ "$KEEPGOING" != "yes" -a ! "$XPKG" ];then
	echo
	echo "Exiting from support/findpkgs, already created up-to-date pkg list:"
	echo " ${STATUSDIR}/findpkgs_FINAL_PKGS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}"
	echo
	exit 0
fi
```
[woof-code/support/findpkgs#L117](https://github.com/puppylinux-woof-CE/woof-CE/blob/a3e9dcecd46cc3095bea0c48ae06ceba7730798b/woof-code/support/findpkgs#L117)

**Comment by peabee** [comment]
busybox.lst is in 00_a32pup_fix and is copied as you say by the modded busybox package template for arch32.

devx is needed for ./3builddistro but not for ./0 ./1 or ./2

**Comment by techrockedge** [comment]
"Please use the 'official' woofce busybox .pet package.."
yes, I am also still seeing this on all the build attempts.

**Comment by s243a** [comment]
I did a trace of the output:

```
bash -x ./2createpackages
...
+ case "$ONEFILE" in
+ read ONEFILE
+ cd /initrd/mnt/dev_save/git_madness/archpup32/woof-CE/woof-out_arch32
+ '[' -d packages-templates/busybox ']'
+ '[' -f packages-templates/busybox_FIXUPHACK ']'
+ echo ' executing packages-templates/busybox_FIXUPHACK'
 executing packages-templates/busybox_FIXUPHACK
+ '[' -d /initrd/mnt/dev_save/git_madness/archpup32/woof-CE/woof-out_arch32/packages-a32pup/busybox ']'
+ cd /initrd/mnt/dev_save/git_madness/archpup32/woof-CE/woof-out_arch32/packages-a32pup/busybox
+ sh /initrd/mnt/dev_save/git_madness/archpup32/woof-CE/woof-out_arch32/packages-templates/busybox_FIXUPHACK
cp: cannot stat '../00_apup32_fix/bin/busybox.lst': No such file or directory
+ '[' -d packages-a32pup/busybox_NULL ']'
+ '[' -d /tmp/busybox ']'
```

If I search for this I find it:
```
# find . -name '*00_apup32_fix*'
./packages-a32pup/00_apup32_fix
```

I think the assumption about the current directory is wrong. I also find this in my trace output:
```
cd /initrd/mnt/dev_save/git_madness/archpup32/woof-CE/woof-out_arch32/packages-a32pup/busybox
```

Maybe the script:
```
woof-out_arch32/packages-templates/busybox_FIXUPHACK
```
should have something like this
```
cd "$(dirname "$0")"
```
https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself

I think I'll give that a try and maybe update the FIXUPHACK with a commit.

**Comment by s243a** [comment]
The fix is; in
```
DISTRO_PKGS_SPECS-arch
```
move the line
```
yes|00_apup32_fix||exe
```
to before the line:
```
yes|busybox|busybox|exe,dev>null,doc,nls
```

I will update this in a commit shortly.

**Comment by s243a** [comment]
This issue is fixed in "[commit f2808bb](https://github.com/techrockedge/archpup32/commit/f2808bb2f7f831ef299486c4ee8c4bc968b8e0a4)"

**Comment by peabee** [comment]
I don't think this is a good idea.......00_fix should be the last entry for ./3builddistro - to fix things....

Suggest run ./2createpackages JUST on 00_fix BEFORE running the global ./2create

**Comment by peabee** [comment]
Ah - no - not first but LAST......

run ./2create on JUST  00_fix AFTER running the global ./2create

**Comment by s243a** [comment]
> I don't think this is a good idea.......00_fix should be the last entry for ./3builddistro - to fix things....
> 
> Suggest run ./2createpackages JUST on 00_fix BEFORE running the global ./2create

Won't running the global ./2create, delete all the previously created packages? perhaps the code in the busybox_FIXUPHACKS could be moved into a 00_apup32_fix_FIXUPHACKS.

**Comment by s243a** [comment]
Re -opened to discuss peabee's comments.

**Comment by peabee** [comment]
> Won't running the global ./2create, delete all the previously created packages?
You're right - dohhh!
The reason it's called 00_ is so it is created before busybox
I don't understand why it isn't being for you....
If I do it manually - 00_ followed by busybox then it works as expected.
The reason for the bodge is that we're using the Arch32 busybox rather than the woof-ce version.
I'll do a test with a cut down DISTRO_PKGS_SPECS-arch

**Comment by peabee** [comment]
OK - problem now understood - ./2create creates in the same order as DISTRO_PKGS_SPECS-arch

FIXUPHACKS do not work for .pets

Need to move the busybox bodge out of 00_fix to a specific busybox bodge pet that can be created before busybox

I'll upload the changes needed later today.

**Comment by s243a** [comment]
> OK - problem now understood - ./2create creates in the same order as DISTRO_PKGS_SPECS-arch
> 
> FIXUPHACKS do not work for .pets
> 
> Need to move the busybox bodge out of 00_fix to a specific busybox bodge pet that can be created before busybox
> 
> I'll upload the changes needed later today.

In the testing branch I created a package called "00_apup32_prefix" which only has the busybox.lst file. Then in your busybox_FIXUPHACKS I pulled the busybox.lst from 00_apup32_prefix rather than 00_apup32_fix

**Comment by peabee** [comment]
crossover............
fixed by 
https://github.com/techrockedge/archpup32/commit/015856a4f2b0d0c61d55ac4f4a4ce98d02002430

**Comment by s243a** [comment]
It looks like we did almost exactly the same thing!
